name: Build AppImage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake pkg-config libglvnd-dev libxcb-ewmh-dev libxcb-icccm4-dev libxcb-res0-dev xwayland libopenxr-dev

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true

      - name: Download linuxdeploy
        run: |
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy-x86_64.AppImage

      - name: Build AppImage
        run: |
          chmod +x build_appimage.sh
          ./build_appimage.sh

      - name: Upload AppImage
        uses: actions/upload-artifact@v3
        with:
          name: Stardust_XR-x86_64.AppImage
          path: Stardust_XR-x86_64.AppImage
